#!/bin/bash

# Install packages
sudo apt-get update
sudo apt-get -y upgrade
sudo apt-get install vim python3-pip awscli virtualenv

# Install Docker
curl -fsSL https://get.docker.com -o get-docker.sh
sh get-docker.sh
sudo usermod -aG docker mario

# Install Pathogen
mkdir -p ~/.vim/autoload ~/.vim/bundle && \
    curl -LSso ~/.vim/autoload/pathogen.vim https://tpo.pe/pathogen.vim

# Install Vim Plugins
git clone https://github.com/fatih/vim-go.git ~/.vim/bundle/vim-go
git clone https://github.com/chriskempson/base16-vim.git ~/.vim/bundle/base16-vim
cp -r dotfiles/ftplugin ~/.vim/ftplugin

# Install Base16 Color Tool
git clone https://github.com/chriskempson/base16-shell.git ~/.config/base16-shell

# Configure git
git config --global user.email "mleone10@gmail.com"
git config --global user.name "Mario Leone"

# Move dotfiles
if [ ! -d dotfiles ]; then
    git clone https://github.com/mleone10/dotfiles.git
fi
cp dotfiles/.bash_profile ~/.bash_profile
cp dotfiles/.vimrc ~/.vimrc
cp -r dotfiles/.aws/ ~/.aws
mkdir -p ~/.vim
